install:
  - yarn install
  - yarn run download
script:
  - yarn run preupload
deploy:
  provider: pages
  skip-cleanup: true
  target-branch: gh-pages
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: docs/
  on:
    branch: master